// DAW/JavaScript/00-Proyectos/23-cotizador-prestamos-react/src/components/Button.jsx
function Button({operador, fn}) {
    return (
        <button
            type='button'
            className='h-10 w-10 flex items-center justify-center font-bold text-white text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500'
            onClick={fn}
        >{operador}</button>
    )
}

export default Button

// DAW/JavaScript/00-Proyectos/24-cotizador-prestamos-vue/src/components/Button.vue
<script setup>
const props = defineProps({
  operador: String,
  fn: Function,
});
</script>

<template>
  <button
    class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
    @click="$emit('fn')"
  >
    {{ operador }}
  </button>
</template>
